/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary":                  "#4b57aa",
        "primary-dim":              "#3f4b9d",
        "primary-container":        "#dfe0ff",
        "on-primary":               "#f9f6ff",
        "on-primary-container":     "#3e4a9c",
        "secondary":                "#466370",
        "secondary-container":      "#c9e7f7",
        "on-secondary-container":   "#395663",
        "secondary-fixed":          "#c9e7f7",
        "on-secondary-fixed":       "#264350",
        "surface":                  "#faf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low":    "#f3f4f3",
        "surface-container":        "#edeeed",
        "surface-container-high":   "#e6e9e8",
        "surface-container-highest":"#dfe3e2",
        "surface-variant":          "#dfe3e2",
        "on-surface":               "#2f3333",
        "on-surface-variant":       "#5b605f",
        "outline":                  "#777c7b",
        "outline-variant":          "#aeb3b2",
        "error":                    "#9e3f4e",
        "error-container":          "#ff8b9a",
        "tertiary":                 "#006f1d",
        "tertiary-container":       "#91f78e",
        "on-tertiary-container":    "#005e17",
        "positive":                 "#10b981",
        "negative":                 "#e11d48",
      },
      fontFamily: {
        "headline": ["Geist", "sans-serif"],
        "body":     ["Geist", "sans-serif"],
        "mono":     ["JetBrains Mono", "monospace"],
        "label":    ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        "sm":      "4px",
        "DEFAULT": "8px",
        "md":      "12px",
        "lg":      "16px",
        "xl":      "16px",
        "full":    "9999px",
      },
    },
  },
  plugins: [],
}
