# Generated by Django 6.0 on 2026-02-22 13:44

import django.db.models.deletion
from django.db import migrations, models


def create_currencies_for_workspaces(apps, schema_editor):
    """Create default currencies for all existing workspaces, plus any symbols in use."""
    Workspace = apps.get_model('workspaces', 'Workspace')
    Currency = apps.get_model('workspaces', 'Currency')

    DEFAULT_CURRENCIES = [
        ('EUR', 'Euro'),
        ('PLN', 'Polish Zloty'),
        ('UAH', 'Ukrainian Hryvnia'),
        ('USD', 'US Dollar'),
    ]
    SYMBOL_NAMES = dict(DEFAULT_CURRENCIES)

    # Collect all currency symbols currently in use across related tables
    all_symbols = set(s for s, _ in DEFAULT_CURRENCIES)

    model_fields = [
        ('budget_accounts', 'BudgetAccount', ['default_currency']),
        ('transactions', 'Transaction', ['currency']),
        ('planned_transactions', 'PlannedTransaction', ['currency']),
        ('currency_exchanges', 'CurrencyExchange', ['from_currency', 'to_currency']),
        ('period_balances', 'PeriodBalance', ['currency']),
        ('budgets', 'Budget', ['currency']),
    ]
    for app_label, model_name, fields in model_fields:
        try:
            Model = apps.get_model(app_label, model_name)
            for field in fields:
                symbols = Model.objects.values_list(field, flat=True).distinct()
                all_symbols.update(s for s in symbols if s)
        except Exception:
            pass

    for workspace in Workspace.objects.all():
        existing = set(Currency.objects.filter(workspace=workspace).values_list('symbol', flat=True))
        for symbol in sorted(all_symbols):
            if symbol and symbol not in existing:
                Currency.objects.create(
                    workspace=workspace,
                    symbol=symbol,
                    name=SYMBOL_NAMES.get(symbol, symbol),
                )


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        ('budget_accounts', '0002_initial'),
        ('budgets', '0003_initial'),
        ('currency_exchanges', '0002_initial'),
        ('period_balances', '0002_initial'),
        ('planned_transactions', '0002_initial'),
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='workspaces.workspace')),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'db_table': 'currencies',
                'ordering': ['symbol'],
                'unique_together': {('symbol', 'workspace')},
            },
        ),
        migrations.RunPython(create_currencies_for_workspaces, migrations.RunPython.noop),
    ]
