# Generated by Django 6.0 on 2026-02-22 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=3, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'db_table': 'currencies',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_currencies', to='workspaces.currency')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_currencies', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'workspace_currencies',
                'unique_together': {('workspace', 'currency')},
            },
        ),
        migrations.AddField(
            model_name='workspace',
            name='currencies',
            field=models.ManyToManyField(blank=True, related_name='workspaces', through='workspaces.WorkspaceCurrency', to='workspaces.currency'),
        ),
    ]
