# Generated by Django 6.0 on 2026-03-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userconsent_user_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='font_family',
            field=models.CharField(choices=[('geist', 'Geist'), ('inter', 'Inter'), ('system', 'System UI'), ('roboto', 'Roboto'), ('lato', 'Lato')], default='geist', help_text='Font family for the user interface', max_length=20),
        ),
    ]
