# Generated by Django 6.0 on 2026-09-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userpreferences_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='font_family',
            field=models.CharField(default='geist', help_text='Font family for the user interface', max_length=20),
        ),
    ]
