# Generated by Django 6.0 on 2026-03-27 20:35

from django.db import migrations, models


def set_existing_verified(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.all().update(email_verified=True)


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_add_font_family_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(set_existing_verified, migrations.RunPython.noop),
    ]
