# Generated by Django 6.0 on 2026-04-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usertwofactor'),
        ('users', '0008_lowercase_emails'),
    ]

    operations = [
    ]
