# Generated by Django 6.0 on 2026-04-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_0007_usertwofactor_0008_lowercase_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='calendar_start_day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1, help_text='First day of the week for calendars (1=Monday, 7=Sunday)'),
        ),
    ]
